// Package webui embeds the built frontend assets into the server binary.
package webui

import (
	"embed"
	"io/fs"
)

// distFS contains files generated by `cd web && npm run build:embed`.
//
//go:embed dist
var distFS embed.FS

// FS returns the embedded frontend dist filesystem when it contains index.html.
func FS() (fs.FS, bool) {
	if _, err := fs.Stat(distFS, "dist/index.html"); err != nil {
		return nil, false
	}

	sub, err := fs.Sub(distFS, "dist")
	if err != nil {
		return nil, false
	}
	return sub, true
}
